CREATE TABLE TB_USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR (80) NOT NULL,
    FULL_NAME VARCHAR (150) NOT NULL,
    EMAIL VARCHAR (150) NULL,
    PASSWORD VARCHAR (10) NOT NULL,
    AGE INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL
);

CREATE TABLE TB_PERSONAL_USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR (80) NOT NULL,
    FULL_NAME VARCHAR (150) NOT NULL,
    EMAIL VARCHAR (150) NULL,
    PASSWORD VARCHAR (10) NOT NULL,
    AGE INTEGER NOT NULL,
    CPF VARCHAR(13) NOT NULL,
    ROLE_ID INTEGER NOT NULL
);

CREATE TABLE TB_JURIDIC_USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR (80) NOT NULL,
    FULL_NAME VARCHAR (150) NOT NULL,
    EMAIL VARCHAR (150) NULL,
    PASSWORD VARCHAR (10) NOT NULL,
    AGE INTEGER NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    ROLE_ID INTEGER NOT NULL
);

CREATE TABLE TB_ADDRESS(
    ID SERIAL PRIMARY KEY,
    COUNTRY VARCHAR(20),
    CITY    VARCHAR(20),
    STREET  VARCHAR(255),
    NEIGHBORHOOD VARCHAR(20),
    STATE VARCHAR(30),
    RESIDENCE_NUMBER INTEGER,
    COMPLEMENT  VARCHAR(20),
    ZIPCODE  INTEGER,
    PRINCIPAL BOOL
);

CREATE TABLE TB_USERS_ADDRESS (
    USER_ID SERIAL NOT NULL,
    ADDRESS_ID SERIAL NOT NULL
);

CREATE TABLE TB_ROLES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR (20) NOT NULL,
    DESCRIPTION VARCHAR (50),
    LEVEL INTEGER NOT NULL
);